/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppResourceEdge implements org.apache.thrift.TBase<AppResourceEdge, AppResourceEdge._Fields>, java.io.Serializable, Cloneable, Comparable<AppResourceEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AppResourceEdge");

  private static final org.apache.thrift.protocol.TField APP_CONTEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("app_context", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField RESOURE_FIELD_DESC = new org.apache.thrift.protocol.TField("resoure", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AppResourceEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AppResourceEdgeTupleSchemeFactory());
  }

  public AppContextID app_context; // required
  public EndPointResourceID resoure; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    APP_CONTEXT((short)1, "app_context"),
    RESOURE((short)2, "resoure");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // APP_CONTEXT
          return APP_CONTEXT;
        case 2: // RESOURE
          return RESOURE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.APP_CONTEXT, new org.apache.thrift.meta_data.FieldMetaData("app_context", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AppContextID.class)));
    tmpMap.put(_Fields.RESOURE, new org.apache.thrift.meta_data.FieldMetaData("resoure", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EndPointResourceID.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AppResourceEdge.class, metaDataMap);
  }

  public AppResourceEdge() {
  }

  public AppResourceEdge(
    AppContextID app_context,
    EndPointResourceID resoure)
  {
    this();
    this.app_context = app_context;
    this.resoure = resoure;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AppResourceEdge(AppResourceEdge other) {
    if (other.isSetApp_context()) {
      this.app_context = new AppContextID(other.app_context);
    }
    if (other.isSetResoure()) {
      this.resoure = new EndPointResourceID(other.resoure);
    }
  }

  public AppResourceEdge deepCopy() {
    return new AppResourceEdge(this);
  }

  @Override
  public void clear() {
    this.app_context = null;
    this.resoure = null;
  }

  public AppContextID getApp_context() {
    return this.app_context;
  }

  public AppResourceEdge setApp_context(AppContextID app_context) {
    this.app_context = app_context;
    return this;
  }

  public void unsetApp_context() {
    this.app_context = null;
  }

  /** Returns true if field app_context is set (has been assigned a value) and false otherwise */
  public boolean isSetApp_context() {
    return this.app_context != null;
  }

  public void setApp_contextIsSet(boolean value) {
    if (!value) {
      this.app_context = null;
    }
  }

  public EndPointResourceID getResoure() {
    return this.resoure;
  }

  public AppResourceEdge setResoure(EndPointResourceID resoure) {
    this.resoure = resoure;
    return this;
  }

  public void unsetResoure() {
    this.resoure = null;
  }

  /** Returns true if field resoure is set (has been assigned a value) and false otherwise */
  public boolean isSetResoure() {
    return this.resoure != null;
  }

  public void setResoureIsSet(boolean value) {
    if (!value) {
      this.resoure = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case APP_CONTEXT:
      if (value == null) {
        unsetApp_context();
      } else {
        setApp_context((AppContextID)value);
      }
      break;

    case RESOURE:
      if (value == null) {
        unsetResoure();
      } else {
        setResoure((EndPointResourceID)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case APP_CONTEXT:
      return getApp_context();

    case RESOURE:
      return getResoure();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case APP_CONTEXT:
      return isSetApp_context();
    case RESOURE:
      return isSetResoure();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AppResourceEdge)
      return this.equals((AppResourceEdge)that);
    return false;
  }

  public boolean equals(AppResourceEdge that) {
    if (that == null)
      return false;

    boolean this_present_app_context = true && this.isSetApp_context();
    boolean that_present_app_context = true && that.isSetApp_context();
    if (this_present_app_context || that_present_app_context) {
      if (!(this_present_app_context && that_present_app_context))
        return false;
      if (!this.app_context.equals(that.app_context))
        return false;
    }

    boolean this_present_resoure = true && this.isSetResoure();
    boolean that_present_resoure = true && that.isSetResoure();
    if (this_present_resoure || that_present_resoure) {
      if (!(this_present_resoure && that_present_resoure))
        return false;
      if (!this.resoure.equals(that.resoure))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(AppResourceEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetApp_context()).compareTo(other.isSetApp_context());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp_context()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.app_context, other.app_context);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResoure()).compareTo(other.isSetResoure());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResoure()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resoure, other.resoure);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AppResourceEdge(");
    boolean first = true;

    sb.append("app_context:");
    if (this.app_context == null) {
      sb.append("null");
    } else {
      sb.append(this.app_context);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("resoure:");
    if (this.resoure == null) {
      sb.append("null");
    } else {
      sb.append(this.resoure);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (app_context == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'app_context' was not present! Struct: " + toString());
    }
    if (resoure == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'resoure' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AppResourceEdgeStandardSchemeFactory implements SchemeFactory {
    public AppResourceEdgeStandardScheme getScheme() {
      return new AppResourceEdgeStandardScheme();
    }
  }

  private static class AppResourceEdgeStandardScheme extends StandardScheme<AppResourceEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AppResourceEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // APP_CONTEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.app_context = new AppContextID();
              struct.app_context.read(iprot);
              struct.setApp_contextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESOURE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.resoure = new EndPointResourceID();
              struct.resoure.read(iprot);
              struct.setResoureIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AppResourceEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.app_context != null) {
        oprot.writeFieldBegin(APP_CONTEXT_FIELD_DESC);
        struct.app_context.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.resoure != null) {
        oprot.writeFieldBegin(RESOURE_FIELD_DESC);
        struct.resoure.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AppResourceEdgeTupleSchemeFactory implements SchemeFactory {
    public AppResourceEdgeTupleScheme getScheme() {
      return new AppResourceEdgeTupleScheme();
    }
  }

  private static class AppResourceEdgeTupleScheme extends TupleScheme<AppResourceEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AppResourceEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.app_context.write(oprot);
      struct.resoure.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AppResourceEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.app_context = new AppContextID();
      struct.app_context.read(iprot);
      struct.setApp_contextIsSet(true);
      struct.resoure = new EndPointResourceID();
      struct.resoure.read(iprot);
      struct.setResoureIsSet(true);
    }
  }

}

