/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DataUnit extends org.apache.thrift.TUnion<DataUnit, DataUnit._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataUnit");
  private static final org.apache.thrift.protocol.TField CLIENT_DATA_UNIT_FIELD_DESC = new org.apache.thrift.protocol.TField("client_data_unit", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField SERVER_DATA_UNIT_FIELD_DESC = new org.apache.thrift.protocol.TField("server_data_unit", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CLIENT_DATA_UNIT((short)1, "client_data_unit"),
    SERVER_DATA_UNIT((short)2, "server_data_unit");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CLIENT_DATA_UNIT
          return CLIENT_DATA_UNIT;
        case 2: // SERVER_DATA_UNIT
          return SERVER_DATA_UNIT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CLIENT_DATA_UNIT, new org.apache.thrift.meta_data.FieldMetaData("client_data_unit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ClientDataUnit.class)));
    tmpMap.put(_Fields.SERVER_DATA_UNIT, new org.apache.thrift.meta_data.FieldMetaData("server_data_unit", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ServerDataUnit.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataUnit.class, metaDataMap);
  }

  public DataUnit() {
    super();
  }

  public DataUnit(_Fields setField, Object value) {
    super(setField, value);
  }

  public DataUnit(DataUnit other) {
    super(other);
  }
  public DataUnit deepCopy() {
    return new DataUnit(this);
  }

  public static DataUnit client_data_unit(ClientDataUnit value) {
    DataUnit x = new DataUnit();
    x.setClient_data_unit(value);
    return x;
  }

  public static DataUnit server_data_unit(ServerDataUnit value) {
    DataUnit x = new DataUnit();
    x.setServer_data_unit(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case CLIENT_DATA_UNIT:
        if (value instanceof ClientDataUnit) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ClientDataUnit for field 'client_data_unit', but got " + value.getClass().getSimpleName());
      case SERVER_DATA_UNIT:
        if (value instanceof ServerDataUnit) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ServerDataUnit for field 'server_data_unit', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case CLIENT_DATA_UNIT:
          if (field.type == CLIENT_DATA_UNIT_FIELD_DESC.type) {
            ClientDataUnit client_data_unit;
            client_data_unit = new ClientDataUnit();
            client_data_unit.read(iprot);
            return client_data_unit;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case SERVER_DATA_UNIT:
          if (field.type == SERVER_DATA_UNIT_FIELD_DESC.type) {
            ServerDataUnit server_data_unit;
            server_data_unit = new ServerDataUnit();
            server_data_unit.read(iprot);
            return server_data_unit;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CLIENT_DATA_UNIT:
        ClientDataUnit client_data_unit = (ClientDataUnit)value_;
        client_data_unit.write(oprot);
        return;
      case SERVER_DATA_UNIT:
        ServerDataUnit server_data_unit = (ServerDataUnit)value_;
        server_data_unit.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case CLIENT_DATA_UNIT:
          ClientDataUnit client_data_unit;
          client_data_unit = new ClientDataUnit();
          client_data_unit.read(iprot);
          return client_data_unit;
        case SERVER_DATA_UNIT:
          ServerDataUnit server_data_unit;
          server_data_unit = new ServerDataUnit();
          server_data_unit.read(iprot);
          return server_data_unit;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CLIENT_DATA_UNIT:
        ClientDataUnit client_data_unit = (ClientDataUnit)value_;
        client_data_unit.write(oprot);
        return;
      case SERVER_DATA_UNIT:
        ServerDataUnit server_data_unit = (ServerDataUnit)value_;
        server_data_unit.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case CLIENT_DATA_UNIT:
        return CLIENT_DATA_UNIT_FIELD_DESC;
      case SERVER_DATA_UNIT:
        return SERVER_DATA_UNIT_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public ClientDataUnit getClient_data_unit() {
    if (getSetField() == _Fields.CLIENT_DATA_UNIT) {
      return (ClientDataUnit)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'client_data_unit' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setClient_data_unit(ClientDataUnit value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CLIENT_DATA_UNIT;
    value_ = value;
  }

  public ServerDataUnit getServer_data_unit() {
    if (getSetField() == _Fields.SERVER_DATA_UNIT) {
      return (ServerDataUnit)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'server_data_unit' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setServer_data_unit(ServerDataUnit value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.SERVER_DATA_UNIT;
    value_ = value;
  }

  public boolean isSetClient_data_unit() {
    return setField_ == _Fields.CLIENT_DATA_UNIT;
  }


  public boolean isSetServer_data_unit() {
    return setField_ == _Fields.SERVER_DATA_UNIT;
  }


  public boolean equals(Object other) {
    if (other instanceof DataUnit) {
      return equals((DataUnit)other);
    } else {
      return false;
    }
  }

  public boolean equals(DataUnit other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(DataUnit other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
