/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EntryInvokeProperty implements org.apache.thrift.TBase<EntryInvokeProperty, EntryInvokeProperty._Fields>, java.io.Serializable, Cloneable, Comparable<EntryInvokeProperty> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EntryInvokeProperty");

  private static final org.apache.thrift.protocol.TField ENTRY_INVOKE_FIELD_DESC = new org.apache.thrift.protocol.TField("entry_invoke", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("property", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EntryInvokePropertyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EntryInvokePropertyTupleSchemeFactory());
  }

  public EntryInvokeID entry_invoke; // required
  public EntryInvokePropertyValue property; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ENTRY_INVOKE((short)1, "entry_invoke"),
    PROPERTY((short)2, "property");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ENTRY_INVOKE
          return ENTRY_INVOKE;
        case 2: // PROPERTY
          return PROPERTY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ENTRY_INVOKE, new org.apache.thrift.meta_data.FieldMetaData("entry_invoke", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntryInvokeID.class)));
    tmpMap.put(_Fields.PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntryInvokePropertyValue.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EntryInvokeProperty.class, metaDataMap);
  }

  public EntryInvokeProperty() {
  }

  public EntryInvokeProperty(
    EntryInvokeID entry_invoke,
    EntryInvokePropertyValue property)
  {
    this();
    this.entry_invoke = entry_invoke;
    this.property = property;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EntryInvokeProperty(EntryInvokeProperty other) {
    if (other.isSetEntry_invoke()) {
      this.entry_invoke = new EntryInvokeID(other.entry_invoke);
    }
    if (other.isSetProperty()) {
      this.property = new EntryInvokePropertyValue(other.property);
    }
  }

  public EntryInvokeProperty deepCopy() {
    return new EntryInvokeProperty(this);
  }

  @Override
  public void clear() {
    this.entry_invoke = null;
    this.property = null;
  }

  public EntryInvokeID getEntry_invoke() {
    return this.entry_invoke;
  }

  public EntryInvokeProperty setEntry_invoke(EntryInvokeID entry_invoke) {
    this.entry_invoke = entry_invoke;
    return this;
  }

  public void unsetEntry_invoke() {
    this.entry_invoke = null;
  }

  /** Returns true if field entry_invoke is set (has been assigned a value) and false otherwise */
  public boolean isSetEntry_invoke() {
    return this.entry_invoke != null;
  }

  public void setEntry_invokeIsSet(boolean value) {
    if (!value) {
      this.entry_invoke = null;
    }
  }

  public EntryInvokePropertyValue getProperty() {
    return this.property;
  }

  public EntryInvokeProperty setProperty(EntryInvokePropertyValue property) {
    this.property = property;
    return this;
  }

  public void unsetProperty() {
    this.property = null;
  }

  /** Returns true if field property is set (has been assigned a value) and false otherwise */
  public boolean isSetProperty() {
    return this.property != null;
  }

  public void setPropertyIsSet(boolean value) {
    if (!value) {
      this.property = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ENTRY_INVOKE:
      if (value == null) {
        unsetEntry_invoke();
      } else {
        setEntry_invoke((EntryInvokeID)value);
      }
      break;

    case PROPERTY:
      if (value == null) {
        unsetProperty();
      } else {
        setProperty((EntryInvokePropertyValue)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ENTRY_INVOKE:
      return getEntry_invoke();

    case PROPERTY:
      return getProperty();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ENTRY_INVOKE:
      return isSetEntry_invoke();
    case PROPERTY:
      return isSetProperty();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EntryInvokeProperty)
      return this.equals((EntryInvokeProperty)that);
    return false;
  }

  public boolean equals(EntryInvokeProperty that) {
    if (that == null)
      return false;

    boolean this_present_entry_invoke = true && this.isSetEntry_invoke();
    boolean that_present_entry_invoke = true && that.isSetEntry_invoke();
    if (this_present_entry_invoke || that_present_entry_invoke) {
      if (!(this_present_entry_invoke && that_present_entry_invoke))
        return false;
      if (!this.entry_invoke.equals(that.entry_invoke))
        return false;
    }

    boolean this_present_property = true && this.isSetProperty();
    boolean that_present_property = true && that.isSetProperty();
    if (this_present_property || that_present_property) {
      if (!(this_present_property && that_present_property))
        return false;
      if (!this.property.equals(that.property))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(EntryInvokeProperty other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEntry_invoke()).compareTo(other.isSetEntry_invoke());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEntry_invoke()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.entry_invoke, other.entry_invoke);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProperty()).compareTo(other.isSetProperty());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProperty()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.property, other.property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EntryInvokeProperty(");
    boolean first = true;

    sb.append("entry_invoke:");
    if (this.entry_invoke == null) {
      sb.append("null");
    } else {
      sb.append(this.entry_invoke);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("property:");
    if (this.property == null) {
      sb.append("null");
    } else {
      sb.append(this.property);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (property != null) {
      property.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EntryInvokePropertyStandardSchemeFactory implements SchemeFactory {
    public EntryInvokePropertyStandardScheme getScheme() {
      return new EntryInvokePropertyStandardScheme();
    }
  }

  private static class EntryInvokePropertyStandardScheme extends StandardScheme<EntryInvokeProperty> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EntryInvokeProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ENTRY_INVOKE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.entry_invoke = new EntryInvokeID();
              struct.entry_invoke.read(iprot);
              struct.setEntry_invokeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.property = new EntryInvokePropertyValue();
              struct.property.read(iprot);
              struct.setPropertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EntryInvokeProperty struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.entry_invoke != null) {
        oprot.writeFieldBegin(ENTRY_INVOKE_FIELD_DESC);
        struct.entry_invoke.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.property != null) {
        oprot.writeFieldBegin(PROPERTY_FIELD_DESC);
        struct.property.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EntryInvokePropertyTupleSchemeFactory implements SchemeFactory {
    public EntryInvokePropertyTupleScheme getScheme() {
      return new EntryInvokePropertyTupleScheme();
    }
  }

  private static class EntryInvokePropertyTupleScheme extends TupleScheme<EntryInvokeProperty> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EntryInvokeProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEntry_invoke()) {
        optionals.set(0);
      }
      if (struct.isSetProperty()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetEntry_invoke()) {
        struct.entry_invoke.write(oprot);
      }
      if (struct.isSetProperty()) {
        struct.property.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EntryInvokeProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.entry_invoke = new EntryInvokeID();
        struct.entry_invoke.read(iprot);
        struct.setEntry_invokeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.property = new EntryInvokePropertyValue();
        struct.property.read(iprot);
        struct.setPropertyIsSet(true);
      }
    }
  }

}

