/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.data;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ApplicationDataUnit implements org.apache.thrift.TBase<ApplicationDataUnit, ApplicationDataUnit._Fields>, java.io.Serializable, Cloneable, Comparable<ApplicationDataUnit> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ApplicationDataUnit");

  private static final org.apache.thrift.protocol.TField ENTRY_INVOKE_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("entry_invoke_property", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField ENTRY_RETURN_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("entry_return_property", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField OPERATION_PROPERTY_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("operation_property_property", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField OPERATION_INVOKE_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("operation_invoke_property", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField OPERATION_RETURN_PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("operation_return_property", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField HOST_APPLICATION_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("host_application_edge", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField APP_RESOURCE_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("app_resource_edge", org.apache.thrift.protocol.TType.STRUCT, (short)7);
  private static final org.apache.thrift.protocol.TField IMPLEMENT_RESOURCE_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("implement_resource_edge", org.apache.thrift.protocol.TType.STRUCT, (short)8);
  private static final org.apache.thrift.protocol.TField ENTRY_INVOKE_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("entry_invoke_edge", org.apache.thrift.protocol.TType.STRUCT, (short)9);
  private static final org.apache.thrift.protocol.TField ENTRY_RETURN_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("entry_return_edge", org.apache.thrift.protocol.TType.STRUCT, (short)10);
  private static final org.apache.thrift.protocol.TField CREATE_INVOCATION_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("create_invocation_edge", org.apache.thrift.protocol.TType.STRUCT, (short)11);
  private static final org.apache.thrift.protocol.TField MAKE_INVOCATION_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("make_invocation_edge", org.apache.thrift.protocol.TType.STRUCT, (short)12);
  private static final org.apache.thrift.protocol.TField CREATE_RESULT_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("create_result_edge", org.apache.thrift.protocol.TType.STRUCT, (short)13);
  private static final org.apache.thrift.protocol.TField RETURN_RESULT_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("return_result_edge", org.apache.thrift.protocol.TType.STRUCT, (short)14);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ApplicationDataUnitStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ApplicationDataUnitTupleSchemeFactory());
  }

  public EntryInvokeProperty entry_invoke_property; // required
  public EntryReturnProperty entry_return_property; // required
  public OperationProperty operation_property_property; // required
  public OperationInvokeProperty operation_invoke_property; // required
  public OperationReturnProperty operation_return_property; // required
  public ServeApplicationEdge host_application_edge; // required
  public ManageResourceEdge app_resource_edge; // required
  public ImplementResourceEdge implement_resource_edge; // required
  public EntryInvokeEdge entry_invoke_edge; // required
  public EntryReturnEdge entry_return_edge; // required
  public CreateInvocationEdge create_invocation_edge; // required
  public MakeInvocationEdge make_invocation_edge; // required
  public CreateResultEdge create_result_edge; // required
  public ReturnResultEdge return_result_edge; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ENTRY_INVOKE_PROPERTY((short)1, "entry_invoke_property"),
    ENTRY_RETURN_PROPERTY((short)2, "entry_return_property"),
    OPERATION_PROPERTY_PROPERTY((short)3, "operation_property_property"),
    OPERATION_INVOKE_PROPERTY((short)4, "operation_invoke_property"),
    OPERATION_RETURN_PROPERTY((short)5, "operation_return_property"),
    HOST_APPLICATION_EDGE((short)6, "host_application_edge"),
    APP_RESOURCE_EDGE((short)7, "app_resource_edge"),
    IMPLEMENT_RESOURCE_EDGE((short)8, "implement_resource_edge"),
    ENTRY_INVOKE_EDGE((short)9, "entry_invoke_edge"),
    ENTRY_RETURN_EDGE((short)10, "entry_return_edge"),
    CREATE_INVOCATION_EDGE((short)11, "create_invocation_edge"),
    MAKE_INVOCATION_EDGE((short)12, "make_invocation_edge"),
    CREATE_RESULT_EDGE((short)13, "create_result_edge"),
    RETURN_RESULT_EDGE((short)14, "return_result_edge");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ENTRY_INVOKE_PROPERTY
          return ENTRY_INVOKE_PROPERTY;
        case 2: // ENTRY_RETURN_PROPERTY
          return ENTRY_RETURN_PROPERTY;
        case 3: // OPERATION_PROPERTY_PROPERTY
          return OPERATION_PROPERTY_PROPERTY;
        case 4: // OPERATION_INVOKE_PROPERTY
          return OPERATION_INVOKE_PROPERTY;
        case 5: // OPERATION_RETURN_PROPERTY
          return OPERATION_RETURN_PROPERTY;
        case 6: // HOST_APPLICATION_EDGE
          return HOST_APPLICATION_EDGE;
        case 7: // APP_RESOURCE_EDGE
          return APP_RESOURCE_EDGE;
        case 8: // IMPLEMENT_RESOURCE_EDGE
          return IMPLEMENT_RESOURCE_EDGE;
        case 9: // ENTRY_INVOKE_EDGE
          return ENTRY_INVOKE_EDGE;
        case 10: // ENTRY_RETURN_EDGE
          return ENTRY_RETURN_EDGE;
        case 11: // CREATE_INVOCATION_EDGE
          return CREATE_INVOCATION_EDGE;
        case 12: // MAKE_INVOCATION_EDGE
          return MAKE_INVOCATION_EDGE;
        case 13: // CREATE_RESULT_EDGE
          return CREATE_RESULT_EDGE;
        case 14: // RETURN_RESULT_EDGE
          return RETURN_RESULT_EDGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ENTRY_INVOKE_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("entry_invoke_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntryInvokeProperty.class)));
    tmpMap.put(_Fields.ENTRY_RETURN_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("entry_return_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntryReturnProperty.class)));
    tmpMap.put(_Fields.OPERATION_PROPERTY_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("operation_property_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationProperty.class)));
    tmpMap.put(_Fields.OPERATION_INVOKE_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("operation_invoke_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationInvokeProperty.class)));
    tmpMap.put(_Fields.OPERATION_RETURN_PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("operation_return_property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationReturnProperty.class)));
    tmpMap.put(_Fields.HOST_APPLICATION_EDGE, new org.apache.thrift.meta_data.FieldMetaData("host_application_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ServeApplicationEdge.class)));
    tmpMap.put(_Fields.APP_RESOURCE_EDGE, new org.apache.thrift.meta_data.FieldMetaData("app_resource_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ManageResourceEdge.class)));
    tmpMap.put(_Fields.IMPLEMENT_RESOURCE_EDGE, new org.apache.thrift.meta_data.FieldMetaData("implement_resource_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ImplementResourceEdge.class)));
    tmpMap.put(_Fields.ENTRY_INVOKE_EDGE, new org.apache.thrift.meta_data.FieldMetaData("entry_invoke_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntryInvokeEdge.class)));
    tmpMap.put(_Fields.ENTRY_RETURN_EDGE, new org.apache.thrift.meta_data.FieldMetaData("entry_return_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EntryReturnEdge.class)));
    tmpMap.put(_Fields.CREATE_INVOCATION_EDGE, new org.apache.thrift.meta_data.FieldMetaData("create_invocation_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CreateInvocationEdge.class)));
    tmpMap.put(_Fields.MAKE_INVOCATION_EDGE, new org.apache.thrift.meta_data.FieldMetaData("make_invocation_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MakeInvocationEdge.class)));
    tmpMap.put(_Fields.CREATE_RESULT_EDGE, new org.apache.thrift.meta_data.FieldMetaData("create_result_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CreateResultEdge.class)));
    tmpMap.put(_Fields.RETURN_RESULT_EDGE, new org.apache.thrift.meta_data.FieldMetaData("return_result_edge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ReturnResultEdge.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ApplicationDataUnit.class, metaDataMap);
  }

  public ApplicationDataUnit() {
  }

  public ApplicationDataUnit(
    EntryInvokeProperty entry_invoke_property,
    EntryReturnProperty entry_return_property,
    OperationProperty operation_property_property,
    OperationInvokeProperty operation_invoke_property,
    OperationReturnProperty operation_return_property,
    ServeApplicationEdge host_application_edge,
    ManageResourceEdge app_resource_edge,
    ImplementResourceEdge implement_resource_edge,
    EntryInvokeEdge entry_invoke_edge,
    EntryReturnEdge entry_return_edge,
    CreateInvocationEdge create_invocation_edge,
    MakeInvocationEdge make_invocation_edge,
    CreateResultEdge create_result_edge,
    ReturnResultEdge return_result_edge)
  {
    this();
    this.entry_invoke_property = entry_invoke_property;
    this.entry_return_property = entry_return_property;
    this.operation_property_property = operation_property_property;
    this.operation_invoke_property = operation_invoke_property;
    this.operation_return_property = operation_return_property;
    this.host_application_edge = host_application_edge;
    this.app_resource_edge = app_resource_edge;
    this.implement_resource_edge = implement_resource_edge;
    this.entry_invoke_edge = entry_invoke_edge;
    this.entry_return_edge = entry_return_edge;
    this.create_invocation_edge = create_invocation_edge;
    this.make_invocation_edge = make_invocation_edge;
    this.create_result_edge = create_result_edge;
    this.return_result_edge = return_result_edge;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ApplicationDataUnit(ApplicationDataUnit other) {
    if (other.isSetEntry_invoke_property()) {
      this.entry_invoke_property = new EntryInvokeProperty(other.entry_invoke_property);
    }
    if (other.isSetEntry_return_property()) {
      this.entry_return_property = new EntryReturnProperty(other.entry_return_property);
    }
    if (other.isSetOperation_property_property()) {
      this.operation_property_property = new OperationProperty(other.operation_property_property);
    }
    if (other.isSetOperation_invoke_property()) {
      this.operation_invoke_property = new OperationInvokeProperty(other.operation_invoke_property);
    }
    if (other.isSetOperation_return_property()) {
      this.operation_return_property = new OperationReturnProperty(other.operation_return_property);
    }
    if (other.isSetHost_application_edge()) {
      this.host_application_edge = new ServeApplicationEdge(other.host_application_edge);
    }
    if (other.isSetApp_resource_edge()) {
      this.app_resource_edge = new ManageResourceEdge(other.app_resource_edge);
    }
    if (other.isSetImplement_resource_edge()) {
      this.implement_resource_edge = new ImplementResourceEdge(other.implement_resource_edge);
    }
    if (other.isSetEntry_invoke_edge()) {
      this.entry_invoke_edge = new EntryInvokeEdge(other.entry_invoke_edge);
    }
    if (other.isSetEntry_return_edge()) {
      this.entry_return_edge = new EntryReturnEdge(other.entry_return_edge);
    }
    if (other.isSetCreate_invocation_edge()) {
      this.create_invocation_edge = new CreateInvocationEdge(other.create_invocation_edge);
    }
    if (other.isSetMake_invocation_edge()) {
      this.make_invocation_edge = new MakeInvocationEdge(other.make_invocation_edge);
    }
    if (other.isSetCreate_result_edge()) {
      this.create_result_edge = new CreateResultEdge(other.create_result_edge);
    }
    if (other.isSetReturn_result_edge()) {
      this.return_result_edge = new ReturnResultEdge(other.return_result_edge);
    }
  }

  public ApplicationDataUnit deepCopy() {
    return new ApplicationDataUnit(this);
  }

  @Override
  public void clear() {
    this.entry_invoke_property = null;
    this.entry_return_property = null;
    this.operation_property_property = null;
    this.operation_invoke_property = null;
    this.operation_return_property = null;
    this.host_application_edge = null;
    this.app_resource_edge = null;
    this.implement_resource_edge = null;
    this.entry_invoke_edge = null;
    this.entry_return_edge = null;
    this.create_invocation_edge = null;
    this.make_invocation_edge = null;
    this.create_result_edge = null;
    this.return_result_edge = null;
  }

  public EntryInvokeProperty getEntry_invoke_property() {
    return this.entry_invoke_property;
  }

  public ApplicationDataUnit setEntry_invoke_property(EntryInvokeProperty entry_invoke_property) {
    this.entry_invoke_property = entry_invoke_property;
    return this;
  }

  public void unsetEntry_invoke_property() {
    this.entry_invoke_property = null;
  }

  /** Returns true if field entry_invoke_property is set (has been assigned a value) and false otherwise */
  public boolean isSetEntry_invoke_property() {
    return this.entry_invoke_property != null;
  }

  public void setEntry_invoke_propertyIsSet(boolean value) {
    if (!value) {
      this.entry_invoke_property = null;
    }
  }

  public EntryReturnProperty getEntry_return_property() {
    return this.entry_return_property;
  }

  public ApplicationDataUnit setEntry_return_property(EntryReturnProperty entry_return_property) {
    this.entry_return_property = entry_return_property;
    return this;
  }

  public void unsetEntry_return_property() {
    this.entry_return_property = null;
  }

  /** Returns true if field entry_return_property is set (has been assigned a value) and false otherwise */
  public boolean isSetEntry_return_property() {
    return this.entry_return_property != null;
  }

  public void setEntry_return_propertyIsSet(boolean value) {
    if (!value) {
      this.entry_return_property = null;
    }
  }

  public OperationProperty getOperation_property_property() {
    return this.operation_property_property;
  }

  public ApplicationDataUnit setOperation_property_property(OperationProperty operation_property_property) {
    this.operation_property_property = operation_property_property;
    return this;
  }

  public void unsetOperation_property_property() {
    this.operation_property_property = null;
  }

  /** Returns true if field operation_property_property is set (has been assigned a value) and false otherwise */
  public boolean isSetOperation_property_property() {
    return this.operation_property_property != null;
  }

  public void setOperation_property_propertyIsSet(boolean value) {
    if (!value) {
      this.operation_property_property = null;
    }
  }

  public OperationInvokeProperty getOperation_invoke_property() {
    return this.operation_invoke_property;
  }

  public ApplicationDataUnit setOperation_invoke_property(OperationInvokeProperty operation_invoke_property) {
    this.operation_invoke_property = operation_invoke_property;
    return this;
  }

  public void unsetOperation_invoke_property() {
    this.operation_invoke_property = null;
  }

  /** Returns true if field operation_invoke_property is set (has been assigned a value) and false otherwise */
  public boolean isSetOperation_invoke_property() {
    return this.operation_invoke_property != null;
  }

  public void setOperation_invoke_propertyIsSet(boolean value) {
    if (!value) {
      this.operation_invoke_property = null;
    }
  }

  public OperationReturnProperty getOperation_return_property() {
    return this.operation_return_property;
  }

  public ApplicationDataUnit setOperation_return_property(OperationReturnProperty operation_return_property) {
    this.operation_return_property = operation_return_property;
    return this;
  }

  public void unsetOperation_return_property() {
    this.operation_return_property = null;
  }

  /** Returns true if field operation_return_property is set (has been assigned a value) and false otherwise */
  public boolean isSetOperation_return_property() {
    return this.operation_return_property != null;
  }

  public void setOperation_return_propertyIsSet(boolean value) {
    if (!value) {
      this.operation_return_property = null;
    }
  }

  public ServeApplicationEdge getHost_application_edge() {
    return this.host_application_edge;
  }

  public ApplicationDataUnit setHost_application_edge(ServeApplicationEdge host_application_edge) {
    this.host_application_edge = host_application_edge;
    return this;
  }

  public void unsetHost_application_edge() {
    this.host_application_edge = null;
  }

  /** Returns true if field host_application_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetHost_application_edge() {
    return this.host_application_edge != null;
  }

  public void setHost_application_edgeIsSet(boolean value) {
    if (!value) {
      this.host_application_edge = null;
    }
  }

  public ManageResourceEdge getApp_resource_edge() {
    return this.app_resource_edge;
  }

  public ApplicationDataUnit setApp_resource_edge(ManageResourceEdge app_resource_edge) {
    this.app_resource_edge = app_resource_edge;
    return this;
  }

  public void unsetApp_resource_edge() {
    this.app_resource_edge = null;
  }

  /** Returns true if field app_resource_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetApp_resource_edge() {
    return this.app_resource_edge != null;
  }

  public void setApp_resource_edgeIsSet(boolean value) {
    if (!value) {
      this.app_resource_edge = null;
    }
  }

  public ImplementResourceEdge getImplement_resource_edge() {
    return this.implement_resource_edge;
  }

  public ApplicationDataUnit setImplement_resource_edge(ImplementResourceEdge implement_resource_edge) {
    this.implement_resource_edge = implement_resource_edge;
    return this;
  }

  public void unsetImplement_resource_edge() {
    this.implement_resource_edge = null;
  }

  /** Returns true if field implement_resource_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetImplement_resource_edge() {
    return this.implement_resource_edge != null;
  }

  public void setImplement_resource_edgeIsSet(boolean value) {
    if (!value) {
      this.implement_resource_edge = null;
    }
  }

  public EntryInvokeEdge getEntry_invoke_edge() {
    return this.entry_invoke_edge;
  }

  public ApplicationDataUnit setEntry_invoke_edge(EntryInvokeEdge entry_invoke_edge) {
    this.entry_invoke_edge = entry_invoke_edge;
    return this;
  }

  public void unsetEntry_invoke_edge() {
    this.entry_invoke_edge = null;
  }

  /** Returns true if field entry_invoke_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetEntry_invoke_edge() {
    return this.entry_invoke_edge != null;
  }

  public void setEntry_invoke_edgeIsSet(boolean value) {
    if (!value) {
      this.entry_invoke_edge = null;
    }
  }

  public EntryReturnEdge getEntry_return_edge() {
    return this.entry_return_edge;
  }

  public ApplicationDataUnit setEntry_return_edge(EntryReturnEdge entry_return_edge) {
    this.entry_return_edge = entry_return_edge;
    return this;
  }

  public void unsetEntry_return_edge() {
    this.entry_return_edge = null;
  }

  /** Returns true if field entry_return_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetEntry_return_edge() {
    return this.entry_return_edge != null;
  }

  public void setEntry_return_edgeIsSet(boolean value) {
    if (!value) {
      this.entry_return_edge = null;
    }
  }

  public CreateInvocationEdge getCreate_invocation_edge() {
    return this.create_invocation_edge;
  }

  public ApplicationDataUnit setCreate_invocation_edge(CreateInvocationEdge create_invocation_edge) {
    this.create_invocation_edge = create_invocation_edge;
    return this;
  }

  public void unsetCreate_invocation_edge() {
    this.create_invocation_edge = null;
  }

  /** Returns true if field create_invocation_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetCreate_invocation_edge() {
    return this.create_invocation_edge != null;
  }

  public void setCreate_invocation_edgeIsSet(boolean value) {
    if (!value) {
      this.create_invocation_edge = null;
    }
  }

  public MakeInvocationEdge getMake_invocation_edge() {
    return this.make_invocation_edge;
  }

  public ApplicationDataUnit setMake_invocation_edge(MakeInvocationEdge make_invocation_edge) {
    this.make_invocation_edge = make_invocation_edge;
    return this;
  }

  public void unsetMake_invocation_edge() {
    this.make_invocation_edge = null;
  }

  /** Returns true if field make_invocation_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetMake_invocation_edge() {
    return this.make_invocation_edge != null;
  }

  public void setMake_invocation_edgeIsSet(boolean value) {
    if (!value) {
      this.make_invocation_edge = null;
    }
  }

  public CreateResultEdge getCreate_result_edge() {
    return this.create_result_edge;
  }

  public ApplicationDataUnit setCreate_result_edge(CreateResultEdge create_result_edge) {
    this.create_result_edge = create_result_edge;
    return this;
  }

  public void unsetCreate_result_edge() {
    this.create_result_edge = null;
  }

  /** Returns true if field create_result_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetCreate_result_edge() {
    return this.create_result_edge != null;
  }

  public void setCreate_result_edgeIsSet(boolean value) {
    if (!value) {
      this.create_result_edge = null;
    }
  }

  public ReturnResultEdge getReturn_result_edge() {
    return this.return_result_edge;
  }

  public ApplicationDataUnit setReturn_result_edge(ReturnResultEdge return_result_edge) {
    this.return_result_edge = return_result_edge;
    return this;
  }

  public void unsetReturn_result_edge() {
    this.return_result_edge = null;
  }

  /** Returns true if field return_result_edge is set (has been assigned a value) and false otherwise */
  public boolean isSetReturn_result_edge() {
    return this.return_result_edge != null;
  }

  public void setReturn_result_edgeIsSet(boolean value) {
    if (!value) {
      this.return_result_edge = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ENTRY_INVOKE_PROPERTY:
      if (value == null) {
        unsetEntry_invoke_property();
      } else {
        setEntry_invoke_property((EntryInvokeProperty)value);
      }
      break;

    case ENTRY_RETURN_PROPERTY:
      if (value == null) {
        unsetEntry_return_property();
      } else {
        setEntry_return_property((EntryReturnProperty)value);
      }
      break;

    case OPERATION_PROPERTY_PROPERTY:
      if (value == null) {
        unsetOperation_property_property();
      } else {
        setOperation_property_property((OperationProperty)value);
      }
      break;

    case OPERATION_INVOKE_PROPERTY:
      if (value == null) {
        unsetOperation_invoke_property();
      } else {
        setOperation_invoke_property((OperationInvokeProperty)value);
      }
      break;

    case OPERATION_RETURN_PROPERTY:
      if (value == null) {
        unsetOperation_return_property();
      } else {
        setOperation_return_property((OperationReturnProperty)value);
      }
      break;

    case HOST_APPLICATION_EDGE:
      if (value == null) {
        unsetHost_application_edge();
      } else {
        setHost_application_edge((ServeApplicationEdge)value);
      }
      break;

    case APP_RESOURCE_EDGE:
      if (value == null) {
        unsetApp_resource_edge();
      } else {
        setApp_resource_edge((ManageResourceEdge)value);
      }
      break;

    case IMPLEMENT_RESOURCE_EDGE:
      if (value == null) {
        unsetImplement_resource_edge();
      } else {
        setImplement_resource_edge((ImplementResourceEdge)value);
      }
      break;

    case ENTRY_INVOKE_EDGE:
      if (value == null) {
        unsetEntry_invoke_edge();
      } else {
        setEntry_invoke_edge((EntryInvokeEdge)value);
      }
      break;

    case ENTRY_RETURN_EDGE:
      if (value == null) {
        unsetEntry_return_edge();
      } else {
        setEntry_return_edge((EntryReturnEdge)value);
      }
      break;

    case CREATE_INVOCATION_EDGE:
      if (value == null) {
        unsetCreate_invocation_edge();
      } else {
        setCreate_invocation_edge((CreateInvocationEdge)value);
      }
      break;

    case MAKE_INVOCATION_EDGE:
      if (value == null) {
        unsetMake_invocation_edge();
      } else {
        setMake_invocation_edge((MakeInvocationEdge)value);
      }
      break;

    case CREATE_RESULT_EDGE:
      if (value == null) {
        unsetCreate_result_edge();
      } else {
        setCreate_result_edge((CreateResultEdge)value);
      }
      break;

    case RETURN_RESULT_EDGE:
      if (value == null) {
        unsetReturn_result_edge();
      } else {
        setReturn_result_edge((ReturnResultEdge)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ENTRY_INVOKE_PROPERTY:
      return getEntry_invoke_property();

    case ENTRY_RETURN_PROPERTY:
      return getEntry_return_property();

    case OPERATION_PROPERTY_PROPERTY:
      return getOperation_property_property();

    case OPERATION_INVOKE_PROPERTY:
      return getOperation_invoke_property();

    case OPERATION_RETURN_PROPERTY:
      return getOperation_return_property();

    case HOST_APPLICATION_EDGE:
      return getHost_application_edge();

    case APP_RESOURCE_EDGE:
      return getApp_resource_edge();

    case IMPLEMENT_RESOURCE_EDGE:
      return getImplement_resource_edge();

    case ENTRY_INVOKE_EDGE:
      return getEntry_invoke_edge();

    case ENTRY_RETURN_EDGE:
      return getEntry_return_edge();

    case CREATE_INVOCATION_EDGE:
      return getCreate_invocation_edge();

    case MAKE_INVOCATION_EDGE:
      return getMake_invocation_edge();

    case CREATE_RESULT_EDGE:
      return getCreate_result_edge();

    case RETURN_RESULT_EDGE:
      return getReturn_result_edge();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ENTRY_INVOKE_PROPERTY:
      return isSetEntry_invoke_property();
    case ENTRY_RETURN_PROPERTY:
      return isSetEntry_return_property();
    case OPERATION_PROPERTY_PROPERTY:
      return isSetOperation_property_property();
    case OPERATION_INVOKE_PROPERTY:
      return isSetOperation_invoke_property();
    case OPERATION_RETURN_PROPERTY:
      return isSetOperation_return_property();
    case HOST_APPLICATION_EDGE:
      return isSetHost_application_edge();
    case APP_RESOURCE_EDGE:
      return isSetApp_resource_edge();
    case IMPLEMENT_RESOURCE_EDGE:
      return isSetImplement_resource_edge();
    case ENTRY_INVOKE_EDGE:
      return isSetEntry_invoke_edge();
    case ENTRY_RETURN_EDGE:
      return isSetEntry_return_edge();
    case CREATE_INVOCATION_EDGE:
      return isSetCreate_invocation_edge();
    case MAKE_INVOCATION_EDGE:
      return isSetMake_invocation_edge();
    case CREATE_RESULT_EDGE:
      return isSetCreate_result_edge();
    case RETURN_RESULT_EDGE:
      return isSetReturn_result_edge();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ApplicationDataUnit)
      return this.equals((ApplicationDataUnit)that);
    return false;
  }

  public boolean equals(ApplicationDataUnit that) {
    if (that == null)
      return false;

    boolean this_present_entry_invoke_property = true && this.isSetEntry_invoke_property();
    boolean that_present_entry_invoke_property = true && that.isSetEntry_invoke_property();
    if (this_present_entry_invoke_property || that_present_entry_invoke_property) {
      if (!(this_present_entry_invoke_property && that_present_entry_invoke_property))
        return false;
      if (!this.entry_invoke_property.equals(that.entry_invoke_property))
        return false;
    }

    boolean this_present_entry_return_property = true && this.isSetEntry_return_property();
    boolean that_present_entry_return_property = true && that.isSetEntry_return_property();
    if (this_present_entry_return_property || that_present_entry_return_property) {
      if (!(this_present_entry_return_property && that_present_entry_return_property))
        return false;
      if (!this.entry_return_property.equals(that.entry_return_property))
        return false;
    }

    boolean this_present_operation_property_property = true && this.isSetOperation_property_property();
    boolean that_present_operation_property_property = true && that.isSetOperation_property_property();
    if (this_present_operation_property_property || that_present_operation_property_property) {
      if (!(this_present_operation_property_property && that_present_operation_property_property))
        return false;
      if (!this.operation_property_property.equals(that.operation_property_property))
        return false;
    }

    boolean this_present_operation_invoke_property = true && this.isSetOperation_invoke_property();
    boolean that_present_operation_invoke_property = true && that.isSetOperation_invoke_property();
    if (this_present_operation_invoke_property || that_present_operation_invoke_property) {
      if (!(this_present_operation_invoke_property && that_present_operation_invoke_property))
        return false;
      if (!this.operation_invoke_property.equals(that.operation_invoke_property))
        return false;
    }

    boolean this_present_operation_return_property = true && this.isSetOperation_return_property();
    boolean that_present_operation_return_property = true && that.isSetOperation_return_property();
    if (this_present_operation_return_property || that_present_operation_return_property) {
      if (!(this_present_operation_return_property && that_present_operation_return_property))
        return false;
      if (!this.operation_return_property.equals(that.operation_return_property))
        return false;
    }

    boolean this_present_host_application_edge = true && this.isSetHost_application_edge();
    boolean that_present_host_application_edge = true && that.isSetHost_application_edge();
    if (this_present_host_application_edge || that_present_host_application_edge) {
      if (!(this_present_host_application_edge && that_present_host_application_edge))
        return false;
      if (!this.host_application_edge.equals(that.host_application_edge))
        return false;
    }

    boolean this_present_app_resource_edge = true && this.isSetApp_resource_edge();
    boolean that_present_app_resource_edge = true && that.isSetApp_resource_edge();
    if (this_present_app_resource_edge || that_present_app_resource_edge) {
      if (!(this_present_app_resource_edge && that_present_app_resource_edge))
        return false;
      if (!this.app_resource_edge.equals(that.app_resource_edge))
        return false;
    }

    boolean this_present_implement_resource_edge = true && this.isSetImplement_resource_edge();
    boolean that_present_implement_resource_edge = true && that.isSetImplement_resource_edge();
    if (this_present_implement_resource_edge || that_present_implement_resource_edge) {
      if (!(this_present_implement_resource_edge && that_present_implement_resource_edge))
        return false;
      if (!this.implement_resource_edge.equals(that.implement_resource_edge))
        return false;
    }

    boolean this_present_entry_invoke_edge = true && this.isSetEntry_invoke_edge();
    boolean that_present_entry_invoke_edge = true && that.isSetEntry_invoke_edge();
    if (this_present_entry_invoke_edge || that_present_entry_invoke_edge) {
      if (!(this_present_entry_invoke_edge && that_present_entry_invoke_edge))
        return false;
      if (!this.entry_invoke_edge.equals(that.entry_invoke_edge))
        return false;
    }

    boolean this_present_entry_return_edge = true && this.isSetEntry_return_edge();
    boolean that_present_entry_return_edge = true && that.isSetEntry_return_edge();
    if (this_present_entry_return_edge || that_present_entry_return_edge) {
      if (!(this_present_entry_return_edge && that_present_entry_return_edge))
        return false;
      if (!this.entry_return_edge.equals(that.entry_return_edge))
        return false;
    }

    boolean this_present_create_invocation_edge = true && this.isSetCreate_invocation_edge();
    boolean that_present_create_invocation_edge = true && that.isSetCreate_invocation_edge();
    if (this_present_create_invocation_edge || that_present_create_invocation_edge) {
      if (!(this_present_create_invocation_edge && that_present_create_invocation_edge))
        return false;
      if (!this.create_invocation_edge.equals(that.create_invocation_edge))
        return false;
    }

    boolean this_present_make_invocation_edge = true && this.isSetMake_invocation_edge();
    boolean that_present_make_invocation_edge = true && that.isSetMake_invocation_edge();
    if (this_present_make_invocation_edge || that_present_make_invocation_edge) {
      if (!(this_present_make_invocation_edge && that_present_make_invocation_edge))
        return false;
      if (!this.make_invocation_edge.equals(that.make_invocation_edge))
        return false;
    }

    boolean this_present_create_result_edge = true && this.isSetCreate_result_edge();
    boolean that_present_create_result_edge = true && that.isSetCreate_result_edge();
    if (this_present_create_result_edge || that_present_create_result_edge) {
      if (!(this_present_create_result_edge && that_present_create_result_edge))
        return false;
      if (!this.create_result_edge.equals(that.create_result_edge))
        return false;
    }

    boolean this_present_return_result_edge = true && this.isSetReturn_result_edge();
    boolean that_present_return_result_edge = true && that.isSetReturn_result_edge();
    if (this_present_return_result_edge || that_present_return_result_edge) {
      if (!(this_present_return_result_edge && that_present_return_result_edge))
        return false;
      if (!this.return_result_edge.equals(that.return_result_edge))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ApplicationDataUnit other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEntry_invoke_property()).compareTo(other.isSetEntry_invoke_property());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEntry_invoke_property()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.entry_invoke_property, other.entry_invoke_property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEntry_return_property()).compareTo(other.isSetEntry_return_property());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEntry_return_property()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.entry_return_property, other.entry_return_property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperation_property_property()).compareTo(other.isSetOperation_property_property());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperation_property_property()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation_property_property, other.operation_property_property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperation_invoke_property()).compareTo(other.isSetOperation_invoke_property());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperation_invoke_property()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation_invoke_property, other.operation_invoke_property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperation_return_property()).compareTo(other.isSetOperation_return_property());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperation_return_property()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation_return_property, other.operation_return_property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHost_application_edge()).compareTo(other.isSetHost_application_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHost_application_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.host_application_edge, other.host_application_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetApp_resource_edge()).compareTo(other.isSetApp_resource_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp_resource_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.app_resource_edge, other.app_resource_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImplement_resource_edge()).compareTo(other.isSetImplement_resource_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImplement_resource_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.implement_resource_edge, other.implement_resource_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEntry_invoke_edge()).compareTo(other.isSetEntry_invoke_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEntry_invoke_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.entry_invoke_edge, other.entry_invoke_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEntry_return_edge()).compareTo(other.isSetEntry_return_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEntry_return_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.entry_return_edge, other.entry_return_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreate_invocation_edge()).compareTo(other.isSetCreate_invocation_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreate_invocation_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.create_invocation_edge, other.create_invocation_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMake_invocation_edge()).compareTo(other.isSetMake_invocation_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMake_invocation_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.make_invocation_edge, other.make_invocation_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreate_result_edge()).compareTo(other.isSetCreate_result_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreate_result_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.create_result_edge, other.create_result_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReturn_result_edge()).compareTo(other.isSetReturn_result_edge());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReturn_result_edge()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.return_result_edge, other.return_result_edge);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ApplicationDataUnit(");
    boolean first = true;

    sb.append("entry_invoke_property:");
    if (this.entry_invoke_property == null) {
      sb.append("null");
    } else {
      sb.append(this.entry_invoke_property);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("entry_return_property:");
    if (this.entry_return_property == null) {
      sb.append("null");
    } else {
      sb.append(this.entry_return_property);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("operation_property_property:");
    if (this.operation_property_property == null) {
      sb.append("null");
    } else {
      sb.append(this.operation_property_property);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("operation_invoke_property:");
    if (this.operation_invoke_property == null) {
      sb.append("null");
    } else {
      sb.append(this.operation_invoke_property);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("operation_return_property:");
    if (this.operation_return_property == null) {
      sb.append("null");
    } else {
      sb.append(this.operation_return_property);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("host_application_edge:");
    if (this.host_application_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.host_application_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("app_resource_edge:");
    if (this.app_resource_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.app_resource_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("implement_resource_edge:");
    if (this.implement_resource_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.implement_resource_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("entry_invoke_edge:");
    if (this.entry_invoke_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.entry_invoke_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("entry_return_edge:");
    if (this.entry_return_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.entry_return_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("create_invocation_edge:");
    if (this.create_invocation_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.create_invocation_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("make_invocation_edge:");
    if (this.make_invocation_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.make_invocation_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("create_result_edge:");
    if (this.create_result_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.create_result_edge);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("return_result_edge:");
    if (this.return_result_edge == null) {
      sb.append("null");
    } else {
      sb.append(this.return_result_edge);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (entry_invoke_property != null) {
      entry_invoke_property.validate();
    }
    if (entry_return_property != null) {
      entry_return_property.validate();
    }
    if (operation_property_property != null) {
      operation_property_property.validate();
    }
    if (operation_invoke_property != null) {
      operation_invoke_property.validate();
    }
    if (operation_return_property != null) {
      operation_return_property.validate();
    }
    if (host_application_edge != null) {
      host_application_edge.validate();
    }
    if (app_resource_edge != null) {
      app_resource_edge.validate();
    }
    if (implement_resource_edge != null) {
      implement_resource_edge.validate();
    }
    if (entry_invoke_edge != null) {
      entry_invoke_edge.validate();
    }
    if (entry_return_edge != null) {
      entry_return_edge.validate();
    }
    if (create_invocation_edge != null) {
      create_invocation_edge.validate();
    }
    if (make_invocation_edge != null) {
      make_invocation_edge.validate();
    }
    if (create_result_edge != null) {
      create_result_edge.validate();
    }
    if (return_result_edge != null) {
      return_result_edge.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ApplicationDataUnitStandardSchemeFactory implements SchemeFactory {
    public ApplicationDataUnitStandardScheme getScheme() {
      return new ApplicationDataUnitStandardScheme();
    }
  }

  private static class ApplicationDataUnitStandardScheme extends StandardScheme<ApplicationDataUnit> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ApplicationDataUnit struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ENTRY_INVOKE_PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.entry_invoke_property = new EntryInvokeProperty();
              struct.entry_invoke_property.read(iprot);
              struct.setEntry_invoke_propertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ENTRY_RETURN_PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.entry_return_property = new EntryReturnProperty();
              struct.entry_return_property.read(iprot);
              struct.setEntry_return_propertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OPERATION_PROPERTY_PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operation_property_property = new OperationProperty();
              struct.operation_property_property.read(iprot);
              struct.setOperation_property_propertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OPERATION_INVOKE_PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operation_invoke_property = new OperationInvokeProperty();
              struct.operation_invoke_property.read(iprot);
              struct.setOperation_invoke_propertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // OPERATION_RETURN_PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operation_return_property = new OperationReturnProperty();
              struct.operation_return_property.read(iprot);
              struct.setOperation_return_propertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // HOST_APPLICATION_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.host_application_edge = new ServeApplicationEdge();
              struct.host_application_edge.read(iprot);
              struct.setHost_application_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // APP_RESOURCE_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.app_resource_edge = new ManageResourceEdge();
              struct.app_resource_edge.read(iprot);
              struct.setApp_resource_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IMPLEMENT_RESOURCE_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.implement_resource_edge = new ImplementResourceEdge();
              struct.implement_resource_edge.read(iprot);
              struct.setImplement_resource_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // ENTRY_INVOKE_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.entry_invoke_edge = new EntryInvokeEdge();
              struct.entry_invoke_edge.read(iprot);
              struct.setEntry_invoke_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // ENTRY_RETURN_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.entry_return_edge = new EntryReturnEdge();
              struct.entry_return_edge.read(iprot);
              struct.setEntry_return_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // CREATE_INVOCATION_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.create_invocation_edge = new CreateInvocationEdge();
              struct.create_invocation_edge.read(iprot);
              struct.setCreate_invocation_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // MAKE_INVOCATION_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.make_invocation_edge = new MakeInvocationEdge();
              struct.make_invocation_edge.read(iprot);
              struct.setMake_invocation_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // CREATE_RESULT_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.create_result_edge = new CreateResultEdge();
              struct.create_result_edge.read(iprot);
              struct.setCreate_result_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // RETURN_RESULT_EDGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.return_result_edge = new ReturnResultEdge();
              struct.return_result_edge.read(iprot);
              struct.setReturn_result_edgeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ApplicationDataUnit struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.entry_invoke_property != null) {
        oprot.writeFieldBegin(ENTRY_INVOKE_PROPERTY_FIELD_DESC);
        struct.entry_invoke_property.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.entry_return_property != null) {
        oprot.writeFieldBegin(ENTRY_RETURN_PROPERTY_FIELD_DESC);
        struct.entry_return_property.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.operation_property_property != null) {
        oprot.writeFieldBegin(OPERATION_PROPERTY_PROPERTY_FIELD_DESC);
        struct.operation_property_property.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.operation_invoke_property != null) {
        oprot.writeFieldBegin(OPERATION_INVOKE_PROPERTY_FIELD_DESC);
        struct.operation_invoke_property.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.operation_return_property != null) {
        oprot.writeFieldBegin(OPERATION_RETURN_PROPERTY_FIELD_DESC);
        struct.operation_return_property.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.host_application_edge != null) {
        oprot.writeFieldBegin(HOST_APPLICATION_EDGE_FIELD_DESC);
        struct.host_application_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.app_resource_edge != null) {
        oprot.writeFieldBegin(APP_RESOURCE_EDGE_FIELD_DESC);
        struct.app_resource_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.implement_resource_edge != null) {
        oprot.writeFieldBegin(IMPLEMENT_RESOURCE_EDGE_FIELD_DESC);
        struct.implement_resource_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.entry_invoke_edge != null) {
        oprot.writeFieldBegin(ENTRY_INVOKE_EDGE_FIELD_DESC);
        struct.entry_invoke_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.entry_return_edge != null) {
        oprot.writeFieldBegin(ENTRY_RETURN_EDGE_FIELD_DESC);
        struct.entry_return_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.create_invocation_edge != null) {
        oprot.writeFieldBegin(CREATE_INVOCATION_EDGE_FIELD_DESC);
        struct.create_invocation_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.make_invocation_edge != null) {
        oprot.writeFieldBegin(MAKE_INVOCATION_EDGE_FIELD_DESC);
        struct.make_invocation_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.create_result_edge != null) {
        oprot.writeFieldBegin(CREATE_RESULT_EDGE_FIELD_DESC);
        struct.create_result_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.return_result_edge != null) {
        oprot.writeFieldBegin(RETURN_RESULT_EDGE_FIELD_DESC);
        struct.return_result_edge.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ApplicationDataUnitTupleSchemeFactory implements SchemeFactory {
    public ApplicationDataUnitTupleScheme getScheme() {
      return new ApplicationDataUnitTupleScheme();
    }
  }

  private static class ApplicationDataUnitTupleScheme extends TupleScheme<ApplicationDataUnit> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ApplicationDataUnit struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEntry_invoke_property()) {
        optionals.set(0);
      }
      if (struct.isSetEntry_return_property()) {
        optionals.set(1);
      }
      if (struct.isSetOperation_property_property()) {
        optionals.set(2);
      }
      if (struct.isSetOperation_invoke_property()) {
        optionals.set(3);
      }
      if (struct.isSetOperation_return_property()) {
        optionals.set(4);
      }
      if (struct.isSetHost_application_edge()) {
        optionals.set(5);
      }
      if (struct.isSetApp_resource_edge()) {
        optionals.set(6);
      }
      if (struct.isSetImplement_resource_edge()) {
        optionals.set(7);
      }
      if (struct.isSetEntry_invoke_edge()) {
        optionals.set(8);
      }
      if (struct.isSetEntry_return_edge()) {
        optionals.set(9);
      }
      if (struct.isSetCreate_invocation_edge()) {
        optionals.set(10);
      }
      if (struct.isSetMake_invocation_edge()) {
        optionals.set(11);
      }
      if (struct.isSetCreate_result_edge()) {
        optionals.set(12);
      }
      if (struct.isSetReturn_result_edge()) {
        optionals.set(13);
      }
      oprot.writeBitSet(optionals, 14);
      if (struct.isSetEntry_invoke_property()) {
        struct.entry_invoke_property.write(oprot);
      }
      if (struct.isSetEntry_return_property()) {
        struct.entry_return_property.write(oprot);
      }
      if (struct.isSetOperation_property_property()) {
        struct.operation_property_property.write(oprot);
      }
      if (struct.isSetOperation_invoke_property()) {
        struct.operation_invoke_property.write(oprot);
      }
      if (struct.isSetOperation_return_property()) {
        struct.operation_return_property.write(oprot);
      }
      if (struct.isSetHost_application_edge()) {
        struct.host_application_edge.write(oprot);
      }
      if (struct.isSetApp_resource_edge()) {
        struct.app_resource_edge.write(oprot);
      }
      if (struct.isSetImplement_resource_edge()) {
        struct.implement_resource_edge.write(oprot);
      }
      if (struct.isSetEntry_invoke_edge()) {
        struct.entry_invoke_edge.write(oprot);
      }
      if (struct.isSetEntry_return_edge()) {
        struct.entry_return_edge.write(oprot);
      }
      if (struct.isSetCreate_invocation_edge()) {
        struct.create_invocation_edge.write(oprot);
      }
      if (struct.isSetMake_invocation_edge()) {
        struct.make_invocation_edge.write(oprot);
      }
      if (struct.isSetCreate_result_edge()) {
        struct.create_result_edge.write(oprot);
      }
      if (struct.isSetReturn_result_edge()) {
        struct.return_result_edge.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ApplicationDataUnit struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(14);
      if (incoming.get(0)) {
        struct.entry_invoke_property = new EntryInvokeProperty();
        struct.entry_invoke_property.read(iprot);
        struct.setEntry_invoke_propertyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.entry_return_property = new EntryReturnProperty();
        struct.entry_return_property.read(iprot);
        struct.setEntry_return_propertyIsSet(true);
      }
      if (incoming.get(2)) {
        struct.operation_property_property = new OperationProperty();
        struct.operation_property_property.read(iprot);
        struct.setOperation_property_propertyIsSet(true);
      }
      if (incoming.get(3)) {
        struct.operation_invoke_property = new OperationInvokeProperty();
        struct.operation_invoke_property.read(iprot);
        struct.setOperation_invoke_propertyIsSet(true);
      }
      if (incoming.get(4)) {
        struct.operation_return_property = new OperationReturnProperty();
        struct.operation_return_property.read(iprot);
        struct.setOperation_return_propertyIsSet(true);
      }
      if (incoming.get(5)) {
        struct.host_application_edge = new ServeApplicationEdge();
        struct.host_application_edge.read(iprot);
        struct.setHost_application_edgeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.app_resource_edge = new ManageResourceEdge();
        struct.app_resource_edge.read(iprot);
        struct.setApp_resource_edgeIsSet(true);
      }
      if (incoming.get(7)) {
        struct.implement_resource_edge = new ImplementResourceEdge();
        struct.implement_resource_edge.read(iprot);
        struct.setImplement_resource_edgeIsSet(true);
      }
      if (incoming.get(8)) {
        struct.entry_invoke_edge = new EntryInvokeEdge();
        struct.entry_invoke_edge.read(iprot);
        struct.setEntry_invoke_edgeIsSet(true);
      }
      if (incoming.get(9)) {
        struct.entry_return_edge = new EntryReturnEdge();
        struct.entry_return_edge.read(iprot);
        struct.setEntry_return_edgeIsSet(true);
      }
      if (incoming.get(10)) {
        struct.create_invocation_edge = new CreateInvocationEdge();
        struct.create_invocation_edge.read(iprot);
        struct.setCreate_invocation_edgeIsSet(true);
      }
      if (incoming.get(11)) {
        struct.make_invocation_edge = new MakeInvocationEdge();
        struct.make_invocation_edge.read(iprot);
        struct.setMake_invocation_edgeIsSet(true);
      }
      if (incoming.get(12)) {
        struct.create_result_edge = new CreateResultEdge();
        struct.create_result_edge.read(iprot);
        struct.setCreate_result_edgeIsSet(true);
      }
      if (incoming.get(13)) {
        struct.return_result_edge = new ReturnResultEdge();
        struct.return_result_edge.read(iprot);
        struct.setReturn_result_edgeIsSet(true);
      }
    }
  }

}

