/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.data;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CreateResultEdge implements org.apache.thrift.TBase<CreateResultEdge, CreateResultEdge._Fields>, java.io.Serializable, Cloneable, Comparable<CreateResultEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CreateResultEdge");

  private static final org.apache.thrift.protocol.TField OPERATION_FIELD_DESC = new org.apache.thrift.protocol.TField("operation", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField OPERATION_RETURN_FIELD_DESC = new org.apache.thrift.protocol.TField("operation_return", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CreateResultEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CreateResultEdgeTupleSchemeFactory());
  }

  public OperationID operation; // required
  public OperationReturnID operation_return; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPERATION((short)1, "operation"),
    OPERATION_RETURN((short)2, "operation_return");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPERATION
          return OPERATION;
        case 2: // OPERATION_RETURN
          return OPERATION_RETURN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPERATION, new org.apache.thrift.meta_data.FieldMetaData("operation", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationID.class)));
    tmpMap.put(_Fields.OPERATION_RETURN, new org.apache.thrift.meta_data.FieldMetaData("operation_return", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationReturnID.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CreateResultEdge.class, metaDataMap);
  }

  public CreateResultEdge() {
  }

  public CreateResultEdge(
    OperationID operation,
    OperationReturnID operation_return)
  {
    this();
    this.operation = operation;
    this.operation_return = operation_return;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CreateResultEdge(CreateResultEdge other) {
    if (other.isSetOperation()) {
      this.operation = new OperationID(other.operation);
    }
    if (other.isSetOperation_return()) {
      this.operation_return = new OperationReturnID(other.operation_return);
    }
  }

  public CreateResultEdge deepCopy() {
    return new CreateResultEdge(this);
  }

  @Override
  public void clear() {
    this.operation = null;
    this.operation_return = null;
  }

  public OperationID getOperation() {
    return this.operation;
  }

  public CreateResultEdge setOperation(OperationID operation) {
    this.operation = operation;
    return this;
  }

  public void unsetOperation() {
    this.operation = null;
  }

  /** Returns true if field operation is set (has been assigned a value) and false otherwise */
  public boolean isSetOperation() {
    return this.operation != null;
  }

  public void setOperationIsSet(boolean value) {
    if (!value) {
      this.operation = null;
    }
  }

  public OperationReturnID getOperation_return() {
    return this.operation_return;
  }

  public CreateResultEdge setOperation_return(OperationReturnID operation_return) {
    this.operation_return = operation_return;
    return this;
  }

  public void unsetOperation_return() {
    this.operation_return = null;
  }

  /** Returns true if field operation_return is set (has been assigned a value) and false otherwise */
  public boolean isSetOperation_return() {
    return this.operation_return != null;
  }

  public void setOperation_returnIsSet(boolean value) {
    if (!value) {
      this.operation_return = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OPERATION:
      if (value == null) {
        unsetOperation();
      } else {
        setOperation((OperationID)value);
      }
      break;

    case OPERATION_RETURN:
      if (value == null) {
        unsetOperation_return();
      } else {
        setOperation_return((OperationReturnID)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OPERATION:
      return getOperation();

    case OPERATION_RETURN:
      return getOperation_return();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OPERATION:
      return isSetOperation();
    case OPERATION_RETURN:
      return isSetOperation_return();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CreateResultEdge)
      return this.equals((CreateResultEdge)that);
    return false;
  }

  public boolean equals(CreateResultEdge that) {
    if (that == null)
      return false;

    boolean this_present_operation = true && this.isSetOperation();
    boolean that_present_operation = true && that.isSetOperation();
    if (this_present_operation || that_present_operation) {
      if (!(this_present_operation && that_present_operation))
        return false;
      if (!this.operation.equals(that.operation))
        return false;
    }

    boolean this_present_operation_return = true && this.isSetOperation_return();
    boolean that_present_operation_return = true && that.isSetOperation_return();
    if (this_present_operation_return || that_present_operation_return) {
      if (!(this_present_operation_return && that_present_operation_return))
        return false;
      if (!this.operation_return.equals(that.operation_return))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CreateResultEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOperation()).compareTo(other.isSetOperation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation, other.operation);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperation_return()).compareTo(other.isSetOperation_return());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperation_return()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation_return, other.operation_return);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CreateResultEdge(");
    boolean first = true;

    sb.append("operation:");
    if (this.operation == null) {
      sb.append("null");
    } else {
      sb.append(this.operation);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("operation_return:");
    if (this.operation_return == null) {
      sb.append("null");
    } else {
      sb.append(this.operation_return);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (operation == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'operation' was not present! Struct: " + toString());
    }
    if (operation_return == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'operation_return' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CreateResultEdgeStandardSchemeFactory implements SchemeFactory {
    public CreateResultEdgeStandardScheme getScheme() {
      return new CreateResultEdgeStandardScheme();
    }
  }

  private static class CreateResultEdgeStandardScheme extends StandardScheme<CreateResultEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CreateResultEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPERATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operation = new OperationID();
              struct.operation.read(iprot);
              struct.setOperationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPERATION_RETURN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operation_return = new OperationReturnID();
              struct.operation_return.read(iprot);
              struct.setOperation_returnIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CreateResultEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.operation != null) {
        oprot.writeFieldBegin(OPERATION_FIELD_DESC);
        struct.operation.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.operation_return != null) {
        oprot.writeFieldBegin(OPERATION_RETURN_FIELD_DESC);
        struct.operation_return.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CreateResultEdgeTupleSchemeFactory implements SchemeFactory {
    public CreateResultEdgeTupleScheme getScheme() {
      return new CreateResultEdgeTupleScheme();
    }
  }

  private static class CreateResultEdgeTupleScheme extends TupleScheme<CreateResultEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CreateResultEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.operation.write(oprot);
      struct.operation_return.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CreateResultEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.operation = new OperationID();
      struct.operation.read(iprot);
      struct.setOperationIsSet(true);
      struct.operation_return = new OperationReturnID();
      struct.operation_return.read(iprot);
      struct.setOperation_returnIsSet(true);
    }
  }

}

