/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.data;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class OperationInvokeProperty implements org.apache.thrift.TBase<OperationInvokeProperty, OperationInvokeProperty._Fields>, java.io.Serializable, Cloneable, Comparable<OperationInvokeProperty> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OperationInvokeProperty");

  private static final org.apache.thrift.protocol.TField OPERATION_INVOKE_FIELD_DESC = new org.apache.thrift.protocol.TField("operation_invoke", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PROPERTY_FIELD_DESC = new org.apache.thrift.protocol.TField("property", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new OperationInvokePropertyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new OperationInvokePropertyTupleSchemeFactory());
  }

  public OperationInvokeID operation_invoke; // required
  public OperationInvokePropertyValue property; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPERATION_INVOKE((short)1, "operation_invoke"),
    PROPERTY((short)2, "property");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPERATION_INVOKE
          return OPERATION_INVOKE;
        case 2: // PROPERTY
          return PROPERTY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPERATION_INVOKE, new org.apache.thrift.meta_data.FieldMetaData("operation_invoke", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationInvokeID.class)));
    tmpMap.put(_Fields.PROPERTY, new org.apache.thrift.meta_data.FieldMetaData("property", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationInvokePropertyValue.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OperationInvokeProperty.class, metaDataMap);
  }

  public OperationInvokeProperty() {
  }

  public OperationInvokeProperty(
    OperationInvokeID operation_invoke,
    OperationInvokePropertyValue property)
  {
    this();
    this.operation_invoke = operation_invoke;
    this.property = property;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OperationInvokeProperty(OperationInvokeProperty other) {
    if (other.isSetOperation_invoke()) {
      this.operation_invoke = new OperationInvokeID(other.operation_invoke);
    }
    if (other.isSetProperty()) {
      this.property = new OperationInvokePropertyValue(other.property);
    }
  }

  public OperationInvokeProperty deepCopy() {
    return new OperationInvokeProperty(this);
  }

  @Override
  public void clear() {
    this.operation_invoke = null;
    this.property = null;
  }

  public OperationInvokeID getOperation_invoke() {
    return this.operation_invoke;
  }

  public OperationInvokeProperty setOperation_invoke(OperationInvokeID operation_invoke) {
    this.operation_invoke = operation_invoke;
    return this;
  }

  public void unsetOperation_invoke() {
    this.operation_invoke = null;
  }

  /** Returns true if field operation_invoke is set (has been assigned a value) and false otherwise */
  public boolean isSetOperation_invoke() {
    return this.operation_invoke != null;
  }

  public void setOperation_invokeIsSet(boolean value) {
    if (!value) {
      this.operation_invoke = null;
    }
  }

  public OperationInvokePropertyValue getProperty() {
    return this.property;
  }

  public OperationInvokeProperty setProperty(OperationInvokePropertyValue property) {
    this.property = property;
    return this;
  }

  public void unsetProperty() {
    this.property = null;
  }

  /** Returns true if field property is set (has been assigned a value) and false otherwise */
  public boolean isSetProperty() {
    return this.property != null;
  }

  public void setPropertyIsSet(boolean value) {
    if (!value) {
      this.property = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OPERATION_INVOKE:
      if (value == null) {
        unsetOperation_invoke();
      } else {
        setOperation_invoke((OperationInvokeID)value);
      }
      break;

    case PROPERTY:
      if (value == null) {
        unsetProperty();
      } else {
        setProperty((OperationInvokePropertyValue)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OPERATION_INVOKE:
      return getOperation_invoke();

    case PROPERTY:
      return getProperty();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OPERATION_INVOKE:
      return isSetOperation_invoke();
    case PROPERTY:
      return isSetProperty();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof OperationInvokeProperty)
      return this.equals((OperationInvokeProperty)that);
    return false;
  }

  public boolean equals(OperationInvokeProperty that) {
    if (that == null)
      return false;

    boolean this_present_operation_invoke = true && this.isSetOperation_invoke();
    boolean that_present_operation_invoke = true && that.isSetOperation_invoke();
    if (this_present_operation_invoke || that_present_operation_invoke) {
      if (!(this_present_operation_invoke && that_present_operation_invoke))
        return false;
      if (!this.operation_invoke.equals(that.operation_invoke))
        return false;
    }

    boolean this_present_property = true && this.isSetProperty();
    boolean that_present_property = true && that.isSetProperty();
    if (this_present_property || that_present_property) {
      if (!(this_present_property && that_present_property))
        return false;
      if (!this.property.equals(that.property))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(OperationInvokeProperty other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOperation_invoke()).compareTo(other.isSetOperation_invoke());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperation_invoke()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operation_invoke, other.operation_invoke);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProperty()).compareTo(other.isSetProperty());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProperty()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.property, other.property);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("OperationInvokeProperty(");
    boolean first = true;

    sb.append("operation_invoke:");
    if (this.operation_invoke == null) {
      sb.append("null");
    } else {
      sb.append(this.operation_invoke);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("property:");
    if (this.property == null) {
      sb.append("null");
    } else {
      sb.append(this.property);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (property != null) {
      property.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OperationInvokePropertyStandardSchemeFactory implements SchemeFactory {
    public OperationInvokePropertyStandardScheme getScheme() {
      return new OperationInvokePropertyStandardScheme();
    }
  }

  private static class OperationInvokePropertyStandardScheme extends StandardScheme<OperationInvokeProperty> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OperationInvokeProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPERATION_INVOKE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operation_invoke = new OperationInvokeID();
              struct.operation_invoke.read(iprot);
              struct.setOperation_invokeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROPERTY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.property = new OperationInvokePropertyValue();
              struct.property.read(iprot);
              struct.setPropertyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OperationInvokeProperty struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.operation_invoke != null) {
        oprot.writeFieldBegin(OPERATION_INVOKE_FIELD_DESC);
        struct.operation_invoke.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.property != null) {
        oprot.writeFieldBegin(PROPERTY_FIELD_DESC);
        struct.property.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OperationInvokePropertyTupleSchemeFactory implements SchemeFactory {
    public OperationInvokePropertyTupleScheme getScheme() {
      return new OperationInvokePropertyTupleScheme();
    }
  }

  private static class OperationInvokePropertyTupleScheme extends TupleScheme<OperationInvokeProperty> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OperationInvokeProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetOperation_invoke()) {
        optionals.set(0);
      }
      if (struct.isSetProperty()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetOperation_invoke()) {
        struct.operation_invoke.write(oprot);
      }
      if (struct.isSetProperty()) {
        struct.property.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OperationInvokeProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.operation_invoke = new OperationInvokeID();
        struct.operation_invoke.read(iprot);
        struct.setOperation_invokeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.property = new OperationInvokePropertyValue();
        struct.property.read(iprot);
        struct.setPropertyIsSet(true);
      }
    }
  }

}

