/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.data;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SqlID implements org.apache.thrift.TBase<SqlID, SqlID._Fields>, java.io.Serializable, Cloneable, Comparable<SqlID> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SqlID");

  private static final org.apache.thrift.protocol.TField DATABASE_URL_FIELD_DESC = new org.apache.thrift.protocol.TField("databaseUrl", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SQL_FIELD_DESC = new org.apache.thrift.protocol.TField("sql", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SqlIDStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SqlIDTupleSchemeFactory());
  }

  public String databaseUrl; // required
  public String sql; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DATABASE_URL((short)1, "databaseUrl"),
    SQL((short)2, "sql");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATABASE_URL
          return DATABASE_URL;
        case 2: // SQL
          return SQL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATABASE_URL, new org.apache.thrift.meta_data.FieldMetaData("databaseUrl", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SQL, new org.apache.thrift.meta_data.FieldMetaData("sql", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SqlID.class, metaDataMap);
  }

  public SqlID() {
  }

  public SqlID(
    String databaseUrl,
    String sql)
  {
    this();
    this.databaseUrl = databaseUrl;
    this.sql = sql;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SqlID(SqlID other) {
    if (other.isSetDatabaseUrl()) {
      this.databaseUrl = other.databaseUrl;
    }
    if (other.isSetSql()) {
      this.sql = other.sql;
    }
  }

  public SqlID deepCopy() {
    return new SqlID(this);
  }

  @Override
  public void clear() {
    this.databaseUrl = null;
    this.sql = null;
  }

  public String getDatabaseUrl() {
    return this.databaseUrl;
  }

  public SqlID setDatabaseUrl(String databaseUrl) {
    this.databaseUrl = databaseUrl;
    return this;
  }

  public void unsetDatabaseUrl() {
    this.databaseUrl = null;
  }

  /** Returns true if field databaseUrl is set (has been assigned a value) and false otherwise */
  public boolean isSetDatabaseUrl() {
    return this.databaseUrl != null;
  }

  public void setDatabaseUrlIsSet(boolean value) {
    if (!value) {
      this.databaseUrl = null;
    }
  }

  public String getSql() {
    return this.sql;
  }

  public SqlID setSql(String sql) {
    this.sql = sql;
    return this;
  }

  public void unsetSql() {
    this.sql = null;
  }

  /** Returns true if field sql is set (has been assigned a value) and false otherwise */
  public boolean isSetSql() {
    return this.sql != null;
  }

  public void setSqlIsSet(boolean value) {
    if (!value) {
      this.sql = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DATABASE_URL:
      if (value == null) {
        unsetDatabaseUrl();
      } else {
        setDatabaseUrl((String)value);
      }
      break;

    case SQL:
      if (value == null) {
        unsetSql();
      } else {
        setSql((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DATABASE_URL:
      return getDatabaseUrl();

    case SQL:
      return getSql();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DATABASE_URL:
      return isSetDatabaseUrl();
    case SQL:
      return isSetSql();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SqlID)
      return this.equals((SqlID)that);
    return false;
  }

  public boolean equals(SqlID that) {
    if (that == null)
      return false;

    boolean this_present_databaseUrl = true && this.isSetDatabaseUrl();
    boolean that_present_databaseUrl = true && that.isSetDatabaseUrl();
    if (this_present_databaseUrl || that_present_databaseUrl) {
      if (!(this_present_databaseUrl && that_present_databaseUrl))
        return false;
      if (!this.databaseUrl.equals(that.databaseUrl))
        return false;
    }

    boolean this_present_sql = true && this.isSetSql();
    boolean that_present_sql = true && that.isSetSql();
    if (this_present_sql || that_present_sql) {
      if (!(this_present_sql && that_present_sql))
        return false;
      if (!this.sql.equals(that.sql))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SqlID other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDatabaseUrl()).compareTo(other.isSetDatabaseUrl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatabaseUrl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.databaseUrl, other.databaseUrl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSql()).compareTo(other.isSetSql());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSql()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sql, other.sql);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SqlID(");
    boolean first = true;

    sb.append("databaseUrl:");
    if (this.databaseUrl == null) {
      sb.append("null");
    } else {
      sb.append(this.databaseUrl);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sql:");
    if (this.sql == null) {
      sb.append("null");
    } else {
      sb.append(this.sql);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SqlIDStandardSchemeFactory implements SchemeFactory {
    public SqlIDStandardScheme getScheme() {
      return new SqlIDStandardScheme();
    }
  }

  private static class SqlIDStandardScheme extends StandardScheme<SqlID> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SqlID struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATABASE_URL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.databaseUrl = iprot.readString();
              struct.setDatabaseUrlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SQL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sql = iprot.readString();
              struct.setSqlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SqlID struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.databaseUrl != null) {
        oprot.writeFieldBegin(DATABASE_URL_FIELD_DESC);
        oprot.writeString(struct.databaseUrl);
        oprot.writeFieldEnd();
      }
      if (struct.sql != null) {
        oprot.writeFieldBegin(SQL_FIELD_DESC);
        oprot.writeString(struct.sql);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SqlIDTupleSchemeFactory implements SchemeFactory {
    public SqlIDTupleScheme getScheme() {
      return new SqlIDTupleScheme();
    }
  }

  private static class SqlIDTupleScheme extends TupleScheme<SqlID> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SqlID struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDatabaseUrl()) {
        optionals.set(0);
      }
      if (struct.isSetSql()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetDatabaseUrl()) {
        oprot.writeString(struct.databaseUrl);
      }
      if (struct.isSetSql()) {
        oprot.writeString(struct.sql);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SqlID struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.databaseUrl = iprot.readString();
        struct.setDatabaseUrlIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sql = iprot.readString();
        struct.setSqlIsSet(true);
      }
    }
  }

}

