/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.event;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HttpResponseEvent implements org.apache.thrift.TBase<HttpResponseEvent, HttpResponseEvent._Fields>, java.io.Serializable, Cloneable, Comparable<HttpResponseEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HttpResponseEvent");

  private static final org.apache.thrift.protocol.TField FRESTO_UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("frestoUUID", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TYPE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("typeName", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField SIGNATURE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("signatureName", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField DEPTH_FIELD_DESC = new org.apache.thrift.protocol.TField("depth", org.apache.thrift.protocol.TType.I32, (short)19);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)31);
  private static final org.apache.thrift.protocol.TField RECEIVED_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("receivedTime", org.apache.thrift.protocol.TType.I64, (short)33);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HttpResponseEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HttpResponseEventTupleSchemeFactory());
  }

  public String frestoUUID; // required
  public String typeName; // required
  public String signatureName; // required
  public int depth; // required
  public long timestamp; // required
  public long receivedTime; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FRESTO_UUID((short)3, "frestoUUID"),
    TYPE_NAME((short)5, "typeName"),
    SIGNATURE_NAME((short)7, "signatureName"),
    DEPTH((short)19, "depth"),
    TIMESTAMP((short)31, "timestamp"),
    RECEIVED_TIME((short)33, "receivedTime");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 3: // FRESTO_UUID
          return FRESTO_UUID;
        case 5: // TYPE_NAME
          return TYPE_NAME;
        case 7: // SIGNATURE_NAME
          return SIGNATURE_NAME;
        case 19: // DEPTH
          return DEPTH;
        case 31: // TIMESTAMP
          return TIMESTAMP;
        case 33: // RECEIVED_TIME
          return RECEIVED_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DEPTH_ISSET_ID = 0;
  private static final int __TIMESTAMP_ISSET_ID = 1;
  private static final int __RECEIVEDTIME_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.RECEIVED_TIME};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FRESTO_UUID, new org.apache.thrift.meta_data.FieldMetaData("frestoUUID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TYPE_NAME, new org.apache.thrift.meta_data.FieldMetaData("typeName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SIGNATURE_NAME, new org.apache.thrift.meta_data.FieldMetaData("signatureName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEPTH, new org.apache.thrift.meta_data.FieldMetaData("depth", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.RECEIVED_TIME, new org.apache.thrift.meta_data.FieldMetaData("receivedTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HttpResponseEvent.class, metaDataMap);
  }

  public HttpResponseEvent() {
  }

  public HttpResponseEvent(
    String frestoUUID,
    String typeName,
    String signatureName,
    int depth,
    long timestamp)
  {
    this();
    this.frestoUUID = frestoUUID;
    this.typeName = typeName;
    this.signatureName = signatureName;
    this.depth = depth;
    setDepthIsSet(true);
    this.timestamp = timestamp;
    setTimestampIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HttpResponseEvent(HttpResponseEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFrestoUUID()) {
      this.frestoUUID = other.frestoUUID;
    }
    if (other.isSetTypeName()) {
      this.typeName = other.typeName;
    }
    if (other.isSetSignatureName()) {
      this.signatureName = other.signatureName;
    }
    this.depth = other.depth;
    this.timestamp = other.timestamp;
    this.receivedTime = other.receivedTime;
  }

  public HttpResponseEvent deepCopy() {
    return new HttpResponseEvent(this);
  }

  @Override
  public void clear() {
    this.frestoUUID = null;
    this.typeName = null;
    this.signatureName = null;
    setDepthIsSet(false);
    this.depth = 0;
    setTimestampIsSet(false);
    this.timestamp = 0;
    setReceivedTimeIsSet(false);
    this.receivedTime = 0;
  }

  public String getFrestoUUID() {
    return this.frestoUUID;
  }

  public HttpResponseEvent setFrestoUUID(String frestoUUID) {
    this.frestoUUID = frestoUUID;
    return this;
  }

  public void unsetFrestoUUID() {
    this.frestoUUID = null;
  }

  /** Returns true if field frestoUUID is set (has been assigned a value) and false otherwise */
  public boolean isSetFrestoUUID() {
    return this.frestoUUID != null;
  }

  public void setFrestoUUIDIsSet(boolean value) {
    if (!value) {
      this.frestoUUID = null;
    }
  }

  public String getTypeName() {
    return this.typeName;
  }

  public HttpResponseEvent setTypeName(String typeName) {
    this.typeName = typeName;
    return this;
  }

  public void unsetTypeName() {
    this.typeName = null;
  }

  /** Returns true if field typeName is set (has been assigned a value) and false otherwise */
  public boolean isSetTypeName() {
    return this.typeName != null;
  }

  public void setTypeNameIsSet(boolean value) {
    if (!value) {
      this.typeName = null;
    }
  }

  public String getSignatureName() {
    return this.signatureName;
  }

  public HttpResponseEvent setSignatureName(String signatureName) {
    this.signatureName = signatureName;
    return this;
  }

  public void unsetSignatureName() {
    this.signatureName = null;
  }

  /** Returns true if field signatureName is set (has been assigned a value) and false otherwise */
  public boolean isSetSignatureName() {
    return this.signatureName != null;
  }

  public void setSignatureNameIsSet(boolean value) {
    if (!value) {
      this.signatureName = null;
    }
  }

  public int getDepth() {
    return this.depth;
  }

  public HttpResponseEvent setDepth(int depth) {
    this.depth = depth;
    setDepthIsSet(true);
    return this;
  }

  public void unsetDepth() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DEPTH_ISSET_ID);
  }

  /** Returns true if field depth is set (has been assigned a value) and false otherwise */
  public boolean isSetDepth() {
    return EncodingUtils.testBit(__isset_bitfield, __DEPTH_ISSET_ID);
  }

  public void setDepthIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DEPTH_ISSET_ID, value);
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public HttpResponseEvent setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public long getReceivedTime() {
    return this.receivedTime;
  }

  public HttpResponseEvent setReceivedTime(long receivedTime) {
    this.receivedTime = receivedTime;
    setReceivedTimeIsSet(true);
    return this;
  }

  public void unsetReceivedTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RECEIVEDTIME_ISSET_ID);
  }

  /** Returns true if field receivedTime is set (has been assigned a value) and false otherwise */
  public boolean isSetReceivedTime() {
    return EncodingUtils.testBit(__isset_bitfield, __RECEIVEDTIME_ISSET_ID);
  }

  public void setReceivedTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RECEIVEDTIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FRESTO_UUID:
      if (value == null) {
        unsetFrestoUUID();
      } else {
        setFrestoUUID((String)value);
      }
      break;

    case TYPE_NAME:
      if (value == null) {
        unsetTypeName();
      } else {
        setTypeName((String)value);
      }
      break;

    case SIGNATURE_NAME:
      if (value == null) {
        unsetSignatureName();
      } else {
        setSignatureName((String)value);
      }
      break;

    case DEPTH:
      if (value == null) {
        unsetDepth();
      } else {
        setDepth((Integer)value);
      }
      break;

    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((Long)value);
      }
      break;

    case RECEIVED_TIME:
      if (value == null) {
        unsetReceivedTime();
      } else {
        setReceivedTime((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FRESTO_UUID:
      return getFrestoUUID();

    case TYPE_NAME:
      return getTypeName();

    case SIGNATURE_NAME:
      return getSignatureName();

    case DEPTH:
      return Integer.valueOf(getDepth());

    case TIMESTAMP:
      return Long.valueOf(getTimestamp());

    case RECEIVED_TIME:
      return Long.valueOf(getReceivedTime());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FRESTO_UUID:
      return isSetFrestoUUID();
    case TYPE_NAME:
      return isSetTypeName();
    case SIGNATURE_NAME:
      return isSetSignatureName();
    case DEPTH:
      return isSetDepth();
    case TIMESTAMP:
      return isSetTimestamp();
    case RECEIVED_TIME:
      return isSetReceivedTime();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HttpResponseEvent)
      return this.equals((HttpResponseEvent)that);
    return false;
  }

  public boolean equals(HttpResponseEvent that) {
    if (that == null)
      return false;

    boolean this_present_frestoUUID = true && this.isSetFrestoUUID();
    boolean that_present_frestoUUID = true && that.isSetFrestoUUID();
    if (this_present_frestoUUID || that_present_frestoUUID) {
      if (!(this_present_frestoUUID && that_present_frestoUUID))
        return false;
      if (!this.frestoUUID.equals(that.frestoUUID))
        return false;
    }

    boolean this_present_typeName = true && this.isSetTypeName();
    boolean that_present_typeName = true && that.isSetTypeName();
    if (this_present_typeName || that_present_typeName) {
      if (!(this_present_typeName && that_present_typeName))
        return false;
      if (!this.typeName.equals(that.typeName))
        return false;
    }

    boolean this_present_signatureName = true && this.isSetSignatureName();
    boolean that_present_signatureName = true && that.isSetSignatureName();
    if (this_present_signatureName || that_present_signatureName) {
      if (!(this_present_signatureName && that_present_signatureName))
        return false;
      if (!this.signatureName.equals(that.signatureName))
        return false;
    }

    boolean this_present_depth = true;
    boolean that_present_depth = true;
    if (this_present_depth || that_present_depth) {
      if (!(this_present_depth && that_present_depth))
        return false;
      if (this.depth != that.depth)
        return false;
    }

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    boolean this_present_receivedTime = true && this.isSetReceivedTime();
    boolean that_present_receivedTime = true && that.isSetReceivedTime();
    if (this_present_receivedTime || that_present_receivedTime) {
      if (!(this_present_receivedTime && that_present_receivedTime))
        return false;
      if (this.receivedTime != that.receivedTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(HttpResponseEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFrestoUUID()).compareTo(other.isSetFrestoUUID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFrestoUUID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.frestoUUID, other.frestoUUID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTypeName()).compareTo(other.isSetTypeName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTypeName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.typeName, other.typeName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSignatureName()).compareTo(other.isSetSignatureName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSignatureName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.signatureName, other.signatureName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDepth()).compareTo(other.isSetDepth());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDepth()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.depth, other.depth);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReceivedTime()).compareTo(other.isSetReceivedTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReceivedTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.receivedTime, other.receivedTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HttpResponseEvent(");
    boolean first = true;

    sb.append("frestoUUID:");
    if (this.frestoUUID == null) {
      sb.append("null");
    } else {
      sb.append(this.frestoUUID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("typeName:");
    if (this.typeName == null) {
      sb.append("null");
    } else {
      sb.append(this.typeName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("signatureName:");
    if (this.signatureName == null) {
      sb.append("null");
    } else {
      sb.append(this.signatureName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("depth:");
    sb.append(this.depth);
    first = false;
    if (!first) sb.append(", ");
    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (isSetReceivedTime()) {
      if (!first) sb.append(", ");
      sb.append("receivedTime:");
      sb.append(this.receivedTime);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (frestoUUID == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'frestoUUID' was not present! Struct: " + toString());
    }
    if (typeName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'typeName' was not present! Struct: " + toString());
    }
    if (signatureName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'signatureName' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'depth' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'timestamp' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HttpResponseEventStandardSchemeFactory implements SchemeFactory {
    public HttpResponseEventStandardScheme getScheme() {
      return new HttpResponseEventStandardScheme();
    }
  }

  private static class HttpResponseEventStandardScheme extends StandardScheme<HttpResponseEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HttpResponseEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 3: // FRESTO_UUID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.frestoUUID = iprot.readString();
              struct.setFrestoUUIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TYPE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.typeName = iprot.readString();
              struct.setTypeNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SIGNATURE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.signatureName = iprot.readString();
              struct.setSignatureNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 19: // DEPTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.depth = iprot.readI32();
              struct.setDepthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 31: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 33: // RECEIVED_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.receivedTime = iprot.readI64();
              struct.setReceivedTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetDepth()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'depth' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTimestamp()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestamp' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HttpResponseEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.frestoUUID != null) {
        oprot.writeFieldBegin(FRESTO_UUID_FIELD_DESC);
        oprot.writeString(struct.frestoUUID);
        oprot.writeFieldEnd();
      }
      if (struct.typeName != null) {
        oprot.writeFieldBegin(TYPE_NAME_FIELD_DESC);
        oprot.writeString(struct.typeName);
        oprot.writeFieldEnd();
      }
      if (struct.signatureName != null) {
        oprot.writeFieldBegin(SIGNATURE_NAME_FIELD_DESC);
        oprot.writeString(struct.signatureName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DEPTH_FIELD_DESC);
      oprot.writeI32(struct.depth);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      if (struct.isSetReceivedTime()) {
        oprot.writeFieldBegin(RECEIVED_TIME_FIELD_DESC);
        oprot.writeI64(struct.receivedTime);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HttpResponseEventTupleSchemeFactory implements SchemeFactory {
    public HttpResponseEventTupleScheme getScheme() {
      return new HttpResponseEventTupleScheme();
    }
  }

  private static class HttpResponseEventTupleScheme extends TupleScheme<HttpResponseEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HttpResponseEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.frestoUUID);
      oprot.writeString(struct.typeName);
      oprot.writeString(struct.signatureName);
      oprot.writeI32(struct.depth);
      oprot.writeI64(struct.timestamp);
      BitSet optionals = new BitSet();
      if (struct.isSetReceivedTime()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetReceivedTime()) {
        oprot.writeI64(struct.receivedTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HttpResponseEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.frestoUUID = iprot.readString();
      struct.setFrestoUUIDIsSet(true);
      struct.typeName = iprot.readString();
      struct.setTypeNameIsSet(true);
      struct.signatureName = iprot.readString();
      struct.setSignatureNameIsSet(true);
      struct.depth = iprot.readI32();
      struct.setDepthIsSet(true);
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.receivedTime = iprot.readI64();
        struct.setReceivedTimeIsSet(true);
      }
    }
  }

}

